VERSION 0.6

IMPORT ./packages/ui-proxy AS ui-proxy

ARG --required DOCKER_REGISTRY_GROUP
ARG --required NEXUS_USER
ARG --required NEXUS_PASSWORD
ARG --required NPM_REGISTRY_GROUP
ARG --required NEXUS_REPOSITORY_URL

test:
  BUILD ui-proxy+test \
    --DOCKER_REGISTRY_GROUP=${DOCKER_REGISTRY_GROUP} \
    --NEXUS_USER=${NEXUS_USER} \
    --NEXUS_PASSWORD=${NEXUS_PASSWORD} \
    --NPM_REGISTRY_GROUP=${NPM_REGISTRY_GROUP} \
    --NEXUS_REPOSITORY_URL=${NEXUS_REPOSITORY_URL}

publish:
  BUILD ui-proxy+publish \
    --DOCKER_REGISTRY_GROUP=${DOCKER_REGISTRY_GROUP} \
    --NEXUS_USER=${NEXUS_USER} \
    --NEXUS_PASSWORD=${NEXUS_PASSWORD} \
    --NPM_REGISTRY_GROUP=${NPM_REGISTRY_GROUP} \
    --NEXUS_REPOSITORY_URL=${NEXUS_REPOSITORY_URL}
