VERSION 0.6

IMPORT ./packages/ui-proxy

ARG --required DOCKER_REGISTRY_GROUP
ARG --required NEXUS_USER
ARG --required NPM_REGISTRY_GROUP
ARG --required NPM_REGISTRY_RELEASES
ARG --required NPM_REGISTRY_SNAPSHOTS
ARG --required NEXUS_REPOSITORY_URL
ARG --required BASE_IMAGES_VERSION

main:
    BUILD ui-proxy+main \
        --DOCKER_REGISTRY_GROUP=${DOCKER_REGISTRY_GROUP} \
        --NEXUS_USER=${NEXUS_USER} \
        --NEXUS_PASSWORD=${NEXUS_PASSWORD} \
        --NPM_REGISTRY_GROUP=${NPM_REGISTRY_GROUP} \
        --NPM_REGISTRY_RELEASES=${NPM_REGISTRY_RELEASES} \
        --NPM_REGISTRY_SNAPSHOTS=${NPM_REGISTRY_SNAPSHOTS} \
        --NEXUS_REPOSITORY_URL=${NEXUS_REPOSITORY_URL} \
        --BASE_IMAGES_VERSION=${BASE_IMAGES_VERSION}
